_target_: pytorch_lightning.Trainer

min_epochs: 1
max_epochs: 10

# progress_bar_refresh_rate: 5
# weights_summary: "full"

deterministic: False

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0
