_target_: src.models.da_frcnn.DaFrcnnDetectionModel

lr: 0.0025
weight_decay: 0.0001

da_net:
  _target_: src.models.modules.da_original.model.DaFRCNN
  backbone_out_channels: 1024
  box_head_res2_out_channels: 256