_target_: src.models.mic_da_frcnn.MicDaFrcnnDetectionModel

lr: 0.0025
weight_decay: 0.0001

da_net:
  _target_: src.models.modules.da_mic.model.MicDaFRCNN
  backbone_out_channels: 256
  consit_weight: 0.1
  img_grl_weight: 0.01
  ins_grl_weight: 0.1